version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: suwon_healing_db
    environment:
      POSTGRES_DB: suwon_healing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - suwon_healing_network

  # Redis (캐싱 및 세션 저장)
  redis:
    image: redis:7-alpine
    container_name: suwon_healing_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - suwon_healing_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: suwon_healing_backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/suwon_healing
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/venv
    depends_on:
      - postgres
      - redis
    networks:
      - suwon_healing_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: suwon_healing_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - suwon_healing_network
    command: npm run dev

  # pgAdmin (데이터베이스 관리 도구)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: suwon_healing_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@suwonhealing.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - suwon_healing_network

volumes:
  postgres_data:
  redis_data:

networks:
  suwon_healing_network:
    driver: bridge

