name = "sw-healing-api"
main = "src/index.js"
compatibility_date = "2025-10-14"

# OpenAPI 스펙 파일 포함
[assets]
directory = "."

[env.development]
name = "dev-sw-healing-api"

[env.development.vars]
CORS_ORIGINS = "https://develop-sw-healing.pages.dev,http://localhost:3000"
DATABASE_URL = "libsql://swhealing-hozza.aws-ap-northeast-1.turso.io"

[env.production]
name = "sw-healing-api"

[env.production.vars]
CORS_ORIGINS = "https://sw-healing.pages.dev,https://app.suwon-healing.com"
DATABASE_URL = "libsql://swhealing-hozza.aws-ap-northeast-1.turso.io"
